### ISSUE TITLE
 zope security proxy doesn't handle __unicode__

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.security#10]
In https://bugs.launchpad.net/zope.security/+bug/1367566, Zach Cashero (zcashero@gmail.com) reported:

> There is no implementation of the `__unicode__` method to handle objects that are wrapped in `the zope.security._proxy._Proxy`. This causes a `UnicodeDecodeError` when trying to get the unicode representation of a custom object that has a security proxy wrapped around it.
> 
> For example, this class implementation:

``` python
class ICustomClass(Interface):
    def __unicode__():
        pass

    def __str__():
        pass

@implementer(ICustomClass)
class CustomClass(object):
    def __unicode__(self):
        print "In __unicode__"
        return u'Español con caracteres especiales'

    def __str__(self):
        print "In __str__"
        return unicode(self).encode('utf-8')
```

> With the associated zcml:
> 
> ``` xml
>   <class class=".test.CustomClass">
>     <allow
>         interface=".test.ICustomClass" />
>   </class>
> ```
> 
> And a simple test:
> 
> ``` python
> >> from zope.security.checker import ProxyFactory
> >> obj = CustomClass()
> >> str(obj)
> In __str__
> In __unicode__
> 'Espa\xc3\xb1ol con caracteres especiales'
> >> unicode(obj)
> In __unicode__
> u'Espa\xf1ol con caracteres especiales'
> >> prox = ProxyFactory(obj)
> >> str(prox)
> In __str__
> In __unicode__
> 'Espa\xc3\xb1ol con caracteres especiales'
> >> unicode(prox)
> In __str__
> In __unicode__
> *** UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
> ```
> 
> The object, that should return a unicode string with special characters works fine on the original object, but causes an error on the proxied object because it actually calls the `__str__` method which returns a `utf-8` encoded byte string and when trying to make it into a unicode string, fails since it is trying to decode it with the system default of `ascii.` Essentially, it is the equivalent of calling:
> 
> ``` python
> >> unicode(prox.__str__())
> In __str__
> In __unicode__
> *** UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
> ```

**Comment by jamadden** [comment]
This was fixed in https://github.com/zopefoundation/zope.proxy/pull/7. The above code now works as expected in the C implementation:
```pycon
>>> type(prox)
zope.security._proxy._Proxy
>>> type(prox).__unicode__
<method '__unicode__' of 'zope.proxy.ProxyBase' objects>
>>> unicode(prox)
In __unicode__
u'Espa\xf1ol con caracteres especiales'
```

It also works if you define `PURE_PYTHON` (or presumably on PyPy) to get the Python implementation:
```pycon
>>> type(prox)
<class 'zope.security.proxy.ProxyPy'>
>>> type(prox).__unicode__
<unbound method ProxyPy.__unicode__>
>>> unicode(prox)
In __unicode__
u'Espa\xf1ol con caracteres especiales'
```

**Comment by jamadden** [comment]
This is now broken again.  The pure-Python checker doesn't allow access to `__unicode__`:

```pycon
>>> from zope.security.checker import ProxyFactory
>>> obj = CustomClass()
>>> str(obj)
In __str__
In __unicode__
'Espa\xc3\xb1ol con caracteres especiales'
>>> unicode(obj)
In __unicode__
u'Espa\xf1ol con caracteres especiales'
>>> prox = ProxyFactory(obj)
>>> type(prox)
<class 'zope.security.proxy.ProxyPy'>
>>> unicode(prox)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//zope.security/src/zope/security/proxy.py", line 32, in _wrapper
    checker.check(wrapped, name)
  File "//zope.security/src/zope/security/checker.py", line 268, in check
    raise ForbiddenAttribute(name, object)
zope.security.interfaces.ForbiddenAttribute: ('__unicode__', <__main__.CustomClass object at 0x109b01590>)
```

The second possible issue is that both the C and Python proxies have stopped calling `__str__` like they did in the example above:
```pycon
>>> str(prox)
'<security proxied __main__.CustomClass instance at 0x109b01590>'
```

Tested with zope.proxy 4.2.1 and 4.3.0 along with master of zope.security. zope.proxy 4.2.1 was current when I wrote the above comment on 2017-09-07, so this is probably a change in zope.security.

**Comment by jamadden** [comment]
In fact I am unable to produce the working examples I gave above with any released combination of zope.security and zope.proxy in a fresh environment. I'm not sure how I got that output in the first place.

**Comment by janwijbrand** [comment]
@jamadden does is help to look a the combination of packages that `grokcore.view` uses to try and reproduce this issue?

**Comment by jamadden** [comment]
The *issue* is easily reproduced. It's the "fix" that I cited in https://github.com/zopefoundation/zope.security/issues/10#issuecomment-327812270 that I can't reproduce, so I can't confirm that it was *ever* fixed for pure-Python.
