### ISSUE TITLE
isinstance(proxied_instance, collections.Mapping) raises TypeError

### ISSUE THREAD

**Issue by cjwatson** [zopefoundation/zope.security#26]
While `isinstance(proxied_instance, cls)` doesn't look through the proxy, my understanding is that it should at least not raise an exception.  However, with Python 2.7.12 and at least zope.security 3.8.3 and 4.1.1:

    >>> import collections
    >>> from zope.security import checker, proxy
    >>> class Foo(object):
    ...     pass
    ... 
    >>> checker.defineChecker(Foo, checker.NamesChecker())
    >>> foo = proxy.ProxyFactory(Foo())
    >>> isinstance(foo, dict)
    False
    >>> isinstance(foo, collections.Mapping)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/cjwatson/proxy/env/lib/python2.7/abc.py", line 145, in __instancecheck__
        return (cls.__subclasscheck__(subclass) or
      File "/home/cjwatson/proxy/env/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/cjwatson/proxy/env/lib/python2.7/abc.py", line 175, in __subclasscheck__
        if issubclass(subclass, rcls):
    TypeError: issubclass() arg 1 must be a class

Python 3.5.2 behaves the same way, with minor differences in the traceback.

This causes a problem when passing proxied objects to `logging` methods, because as of Python 2.7.7 (https://bugs.python.org/issue21172) `LogRecord.__init__` calls `isinstance(args[0], collections.Mapping)` rather than the previous `isinstance(args[0], dict)` to check whether a dictionary was passed.  We ran into this in Launchpad when some of our job runners started crashing after a much-delayed upgrade from Python 2.7.3 to 2.7.11.

**Comment by jamadden** [comment]
I've [run into this before](https://github.com/zopefoundation/zope.app.component/pull/1#issuecomment-297836601). There I was able to change the code to remove the proxy and avoid the problem, but I didn't come up with a general solution. I don't think we want security proxies to stop wrapping `__class__` by default.

I can think of a couple possible workarounds here. One could monkey-patch `logging` to use `zope.security.proxy.isinstance`:
```python
import zope.security.proxy
import logging
logging.isinstance = zope.security.proxy.isinstance
```

Or one could call `logging.setLogRecordFactory` to use a custom `LogRecord` that removes the security proxy before passing it to the super class (of course there are security implications of that).

**Comment by icemac** [comment]
@jamadden Should your suggestion be documented in this package or are there other possible solutions?

**Comment by jamadden** [comment]
@icemac I haven't thought of any other general solutions. For this specific problem, this package could perhaps provide the custom `LogRecord` subclass. I do agree that the trouble with proxies, `isinstance`, and (specifically) ABC classes could be (better) documented but it's not entirely clear where to put it.

**Comment by icemac** [comment]
Maybe a special "hints" subsection of http://zopesecurity.readthedocs.io could be a good place, at least for people who found out that the security proxy is the source of the logging problem.

**Comment by jamadden** [comment]
I've got two PR's open (#38 and #39) and after their resolution I will take a look at improving docs.

**Comment by jamadden** [comment]
Ironically, while working on documenting this, I ran into this exact issue. I tried to document `zope.security.checker.CheckerPublic` (which happens to be a Proxy around a Global object) and got:
```
WARNING: //docs/api/checker.rst:11: (WARNING/2) autodoc: failed to import data 'CheckerPublic' from module 'zope.security.checker'; the following exception was raised:
Traceback (most recent call last):
  File "//lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 665, in import_object
    logger.debug('[autodoc] => %r', obj)
  File "//3.6/lib/python3.6/logging/__init__.py", line 1628, in debug
    self.log(DEBUG, msg, *args, **kwargs)
  File "//lib/python3.6/site-packages/sphinx/util/logging.py", line 97, in log
    super(SphinxLoggerAdapter, self).log(level, msg, *args, **kwargs)
  File "//3.6/lib/python3.6/logging/__init__.py", line 1672, in log
    self.logger._log(level, msg, args, **kwargs)
  File "//3.6/lib/python3.6/logging/__init__.py", line 1441, in _log
    exc_info, func, extra, sinfo)
  File "//3.6/lib/python3.6/logging/__init__.py", line 1411, in makeRecord
    sinfo)
  File "//3.6/lib/python3.6/logging/__init__.py", line 277, in __init__
    if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
  File "/../lib/python3.6/abc.py", line 191, in __instancecheck__
    return any(cls.__subclasscheck__(c) for c in {subclass, subtype})
  File "/../lib/python3.6/abc.py", line 191, in <genexpr>
    return any(cls.__subclasscheck__(c) for c in {subclass, subtype})
  File "/../lib/python3.6/abc.py", line 220, in __subclasscheck__
    if issubclass(subclass, rcls):
TypeError: issubclass() arg 1 must be a class
```

**Comment by mgedmin** [comment]
Can't we do something with `__subclasshook__()` to avoid the TypeError?

**Comment by mgedmin** [comment]
Ah, no -- `__subclasscheck__` comes from the 2nd `issubclass()` argument, so nothing we do to the 1st one affects it.

*sigh*

**Comment by jamadden** [comment]
I don't think so. `isinstance(proxy,  collections.Mapping)` calls `collections.Mapping.__instancecheck__` (which is `abc.ABCMeta.__instancecheck__`), which then calls `collections.Mapping.__subclasscheck__` with `proxy.__class__`. That ultimately winds up calling `issubclass(proxy.__class__, <some random type>)`

I don't think the left-hand argument ever gets a say in the process, it's all on the type being checked, the right-hand argument.

**Comment by jamadden** [comment]
It's interesting that `abc.ABCMeta.__instancecheck__` specifically supports the case that `obj.__class__` and `type(obj)` are different.

We could monkey-patch `abc.ABCMeta.__instancecheck__` to unwrap its first argument...or, at least, to pass an object with a `__class__` equivalent to the proxied object's `__class__`. Since nothing is ever done to that `__class__`, other than calling `issubclass()` with it as the first argument, that should be safe from a security perspective (?). Something like (ignoring old-style instances for now):

```python
import abc
check = abc.ABCMeta.__instancecheck__
class ClassProxy(object):
    pass
from zope.proxy import Proxy
from zope.security.proxy import removeSecurityProxy

def __instancecheck__(cls, instance):
   if issubclass(type(instance), Proxy):
      instance = ClassProxy()
      instance.__class__ = removeSecurityProxy(instance).__class__
    return check(cls, instance)

abc.ABCMeta.__instancecheck__ = __instancecheck__
```

Monkey-patching isn't popular and can be confusing, but that would probably work. I don't know if the cost is worth it though.

**Comment by mgedmin** [comment]
> It's interesting that abc.ABCMeta.__instancecheck__ specifically supports the case that obj.__class__ and type(obj) are different.

Old-style classes in Python 2 behave this way: `type(instance)` is `instance`, while `instance.__class__` is the (old-style) class.

-----

FWIW I'm :-1: for monkey-patching the stdlib at import time, +0 for having a helper function that the application developer may call if they want to enable the monkey-patch for the app.

**Comment by jamadden** [comment]
> Old-style classes in Python 2 behave this way: type(obj) is types.InstanceType, while obj.__class__ is the (old-style) class.

Interesting. It does allow for that on Python 2: `if type(instance) is InstanceType: subtype = instance.__class__` (so it ends up checking `instance.__class__` twice). But the really interesting thing is that it still does [check both on Python 3](https://github.com/python/cpython/blob/3.6/Lib/abc.py#L181), and the `__class__` takes priority.

----

> FWIW I'm :-1: for monkey-patching the stdlib at import time,

Me too.

> +0 for having a helper function that the application developer may call if they want to enable the monkey-patch for the app.

In this specific case, I suspect that patching `isinstance` in the logging module is the better (safer, less intrusive) way to go (and that takes no more code than importing and calling a patching function). For many cases, `from zope.security.proxy import isinstance` will be the correct thing to do. I suspect others are best dealt with on a case-by-case (call-by-call) basis; I think an application that wants to globally patch `ABCMeta` would be extremely rare, rare enough that we probably don't need a helper here. This issue and discussion is now linked from the docs, so it can serve as a source of recipes for things that aren't covered there (I didn't suggest the ABCMeta patch in the docs because it seems like overkill).
