### ISSUE TITLE
Proxied zope.interface.Provides and implementedBy can't be put in a list in Python 3 but can in Py2

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.security#27]
This is similar to #23 and #20, except with `__len__`, not `__iter__`. And it only happens in Python 3.

When you write `list(thing)` in CPython 3, CPython will look for the `__len__` slot in the C struct for the object's type. If that's filled in, and calling it raises any exception besides a `TypeError`, that exception is propageted. This is implemented in `Objects/abstract.c:PyObject_LengthHint`. This is defined in [PEP 424](https://www.python.org/dev/peps/pep-0424/) and implemented in Python 3.4.

In Python 2.7 and earlier, there is a private CPython function `_PyObject_LengthHint` that ignores both `TypeError` and `AttributeError` when it tries to get the `__len__`. zope.security's `ForbiddenAttribute` exception derives from `AttributeError` and so is ignored for this purpose.

Here's sample code:

```python
from zope.security.proxy import Proxy
from zope.security.checker import Checker
from zope.security.checker import CheckerPublic

from zope.interface import providedBy
from zope.interface import alsoProvides
from zope.interface import implementer
from zope.interface import Interface

class I1(Interface):
	pass

class I2(Interface):
	pass

@implementer(I1)
class O(object):
	pass

o = O()
# alsoProvides(o, I2)

checker = Checker({})

proxy = Proxy(o, checker)

list(providedBy(proxy))
```

Under Python 3.4+ this raises (PURE_PYTHON used for a slightly more clear stack trace; the same thing happens with all the C extensions in place):
```
PURE_PYTHON=1 python /tmp/test.py
Traceback (most recent call last):
  File "/tmp/test.py", line 22, in <module>
    list(providedBy(proxy))
  File "//lib/python3.5/site-packages/zope/security/proxy.py", line 28, in _wrapper
    checker.check(wrapped, name)
  File "//lib/python3.5/site-packages/zope/security/checker.py", line 229, in check
    raise ForbiddenAttribute(name, object)
zope.security.interfaces.ForbiddenAttribute: ('__len__', <implementedBy __main__.O>)
```

If you uncomment the `alsoProvides` line, you get a similar but different exception:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 27, in <module>
    list(providedBy(proxy))
  File "//lib/python3.5/site-packages/zope/security/proxy.py", line 28, in _wrapper
    checker.check(wrapped, name)
  File "//lib/python3.5/site-packages/zope/security/checker.py", line 229, in check
    raise ForbiddenAttribute(name, object)
zope.security.interfaces.ForbiddenAttribute: ('__len__', <zope.interface.Provides object at 0x1060f2048>)
```

**Under Python 2.7, these both run just fine.**

How should we address this discrepancy (assuming we should)? 

* Should we keep playing whack-a-mole and add those two types of objects to the set for which `_iteratorChecker` is used by default? 
* Or should we alter the `Checker` implementation to ignore requests for `__len__`, as it already does for `__iter__`? 
* Or maybe these two types of objects (the attributes) shouldn't be wrapped in proxies at all? (I don't think we trivially have that capability.)
* Other options?

If we do anything, we should probably also adapt the same solution for the other half of PEP424 and do the same thing for the `__length_hint__` method.

I ran into this considering a potential efficiency change in `zope.app.apidoc`.

**Comment by icemac** [comment]
@jamadden Your first suggestion seems to be the easiest one to implement and it does not open up other potential issues when not security checking another method. (If I understand you correctly.)

**Comment by jamadden** [comment]
I'll work up another whack-a-mole ( 😉 ) PR implementing that first suggestion.

**Comment by jamadden** [comment]
While fixing this, I discovered that `__length_hint__` is simply not honored at all. I thought it was a problem in plain zope.proxy, but it seems localized here.
