### ISSUE TITLE
 IPrincipal.id should be BytesLine (or ASCIILine)

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.security#4]
In https://bugs.launchpad.net/zope.security/+bug/98265, @philikon reported:

> The IPrincipal interface specifies a wrong field type for the 'id' attribute of principals. Currently it uses a TextLine (which means a unicode string not containing a new-line character).
> 
> There are several places within Zope 3 that make the assumption that the principal id is NOT unicode. One of the places is the adapter from IPrincipal to ILoggingInfo that simply str()s the principal.id (see zope.app.security.principallogging.PrincipalLogging.getLogMessage).  Another, much more important place is Zope's default publication which sets the principal.id as the user name on the transaction (see zope.app.publication.zopepublication.ZopePublication.annotateTransaction).  The docstring to ITransaction.setUser, however, definitely states that whatever is passed in as a user name must be str()able.
> 
> This problem is not apparent with principals defined through ZCML because the <zope:principal /> directive's 'id' parameter is specified as a zope.schema.Id field which inherits from BytesLine. That means ZCML-defined principals' ids are always str()able. The IPrincipal.id field specification is a problem with principals defined TTW where the IPrincipal interface is used as a schema for form generation, for example. Creating a TTW-defined principal with an id containing 'günter' for example is quite possible but when logging in with this principal, you'll get the following error:

``` python
2005-12-09T13:22:15 ERROR SiteError http://localhost:8080
Traceback (most recent call last):
  ...
  File ".../zope/app/security/principallogging.py", line 29, in getLogMessage
    return str(self.principal.id)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 10: ordinal not in range(128)
```

> Now, if you work around this problem by registering a stub ILoggingInfo adapter, the ZODB will complain:

``` python
2005-12-10T13:33:40 ERROR SiteError http://localhost:8080/@@loginForm.html
Traceback (most recent call last):
  ...
  File ".../ZODB/FileStorage/format.py", line 350, in asString
    return "".join(map(str, [s, self.user, self.descr, self.ext]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 12: ordinal not in range(128)
```

> Or, in case of DirectoryStorage:

``` python
2005-12-09T11:57:53 ERROR SiteError http://localhost:8080/@@loginForm.html
Traceback (most recent call last):
  ...
  File ".../DirectoryStorage/Full.py", line 188, in _vote_impl
    body = struct.pack("!HHHIH",len(u),len(d),len(e),len(ob),0) + u + d + e + ob
UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 5: ordinal not in range(128)
```

> The IPrincipal interface should be changed so that the 'id' attribute is at least a BytesLine field (not a TextLine anymore) to ensure the necessary str()ability. Perhaps it should even be an ASCIILine since characters >127 are pretty meaningless without the corresponding encoding information. Same goes for zope.schema.Id, URI, DottedName fields which all inherit from BytesLine, but that's material for another issue.

@faassen followed up:

> Since Zope already makes the assumption that these ids are not unicode, it's unlikely that unicode ids are sitting in production databases. This therefore should be fixable safely in 3.2.

@jimfulton replied:

> This is a much bigger topic than it appears to be. For example, it's not entirely clear what the requirement for ids in http and database logs. The common log file format is space delimited, so you don't want spaces in ids. Also, if we switch to ids like "42". I suspect the usefulness of the information in logs will be diminished.
> 
> (For ZODB, I'd like to move toward putting principal informaton in the extension data. If we did that, then there wouldn't be any restriction except on pickability and size.)
> 
> BTW, should ids be size limited?
> 
> This needs more thought.
> 
> For now, I'm gonna "resolve" this by:
> - updating the name chooser to accept names up to 100 characters than contain printable non-space 7-bit ASCII characters.
>   
>   (Revision 40889)

**Comment by jamadden** [comment]
This was originally opened in, and all of the comments are from, 2005. Since then a lot of things have changed:

- The zope.* packages as well as ZODB and RelStorage have been updated to work with Python 3. This means they typically have a much better understanding of `text` vs `bytes` and when each is appropriate. 
- `Id` now derives from `NativeTextLine` so it means a different thing on each platform. Again, code must be aware of that fact. Python 2 is slowly on the way out, so unicode `id` values are becoming the default.
- The specific example of `PrincipalLogger.getLogMessage` now handles this like so:
```python
    def getLogMessage(self):
        pid = self.principal.id
        return pid.encode('ascii', 'backslashreplace')
```

At this point, if anything needs changed I would argue that it's the `<zope:principal>` directive (which now lives in `zope.principalregistry`): It still defines `id` as `Id`, a NativeTextLine, so when it ultimately creates the `Principal` instance object on Python 2 it seems likely that it winds up having an `id` that is `bytes`, in violation of the schema.

I think this can safely be closed as having been dealt with other places by now. If not, feel free to re-open.
