### ISSUE TITLE
RTD builds broken

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.security#44]
See [here](http://readthedocs.org/projects/zopesecurity/builds/5981855/). It looks like the "install this project" button needs to be checked. @tseaver could you take a look please?

```
  File "conf.py", line 19, in <module>
    rqmt = pkg_resources.require('zope.security')[0]
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopesecurity/envs/latest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopesecurity/envs/latest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'zope.security' distribution was not found and is required by the application
```

It also seems like there's something wrong with the webhook; I had to manually trigger the latest build.

**Comment by tseaver** [comment]
Hmm. the API docs looked fine to me.  Nevertheles, I've updated the RTD project to install `zope.security`.

**Comment by jamadden** [comment]
The last time they had been built was over 2.5 years ago, so updates weren't getting sent out. I noticed this working on #26 when I added a large new section to the docs (http://zopesecurity.readthedocs.io/en/latest/proxy.html#known-issues-with-proxies). 

But now it's there and all is right with the world. Thank you!
