### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.security#45]
We've got a lot of changes built up for 4.2.0. It would probably be good to get those out there soon.

**Comment by mgedmin** [comment]
You have PyPI rights now.

**Comment by jamadden** [comment]
Thank you. I'd like to hold off on actually releasing for a bit in hopes that we can get #44 resolved so that fresh documentation goes out too.

**Comment by jamadden** [comment]
I got tired of waiting :) 4.2.0 has been released to PyPI. Thanks again!
