### ISSUE TITLE
Installing zope.sucurity behind proxy fails

### ISSUE THREAD

**Issue by nagado** [zopefoundation/zope.security#47]
Poor souls working on corporate servers behind proxy will have this fail with this (as downloading packages straight from the internet isn't an option or those):
Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/zope.proxy/: [Errno 101] Network is unreachable -- Some packages may not be found!
    Couldn't find index page for 'zope.proxy' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
    No local packages or working download links found for zope.proxy>=4.3.0

This issue started coming up somewhat recently. Installing zope.proxy separately works as it is installed properly through the requirements

**Comment by jamadden** [comment]
What command are you using to install zope.proxy? Is this a buildout or a modern version of pip?

**Comment by nagado** [comment]
It is installed with pip install from a requirements file, with --trusted-hosts provided for what options for downloading packages we have behind the proxy. The package zope.proxy is easily installed if added to the requirements, but it fails when zope.security discovers it's missing. This link shouldn't be even a part of the install in any way " https://pypi.python.org/simple/zope.proxy/", but it does come up in the error.
Pip version: 8.1.1

**Comment by jamadden** [comment]
This is a fairly common problem with pip and `setup_requires`: pip doesn't handle the `setup_requires`, that's entirely on setuptools. And if you've only configured *pip* to deal with proxies, then setuptools doesn't know anything about them.

pip documents what to do about that [here](https://pip.pypa.io/en/latest/reference/pip_install/#controlling-setup-requires). (Or, as you noticed, you can simply fullfill the setup_requires dependency first by explicitly listing it.)

**Comment by tseaver** [comment]
@nagado Thanks for the report!  ISTM that the pip documentation which @jamadden linked addresses the usecase, so I'm closing the issue.  Please feel free to reopen if it doesn't work for you.
