### ISSUE TITLE
 No checking policy for itertools.groupby

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.security#9]
In https://bugs.launchpad.net/zope.security/+bug/645469, Aaron Bentley (aaron.bentley@canonical.com) reported:

> `itertools.groupby` is a built-in custom iterator type introduced in python2.4. It should have the same checker as other built-in iterators.
> 
> Also, `itertools._grouper` also needs to be exposed as an iterator. Its type is not exposed by name, but can be accessed like so: `type(list(itertools.groupby([0]))[0][1])`

**Comment by jamadden** [comment]
Fixed in #29.
